name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 
    - name: Build the Docker image
      run: |
        docker build . --tag pythonmain:latest
      
    - name: Log in to Docker registry
      uses: docker/login-action@v1  
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Push Docker image
      run: |
        docker tag pythonmain:latest rishabhverma99/my-project-pipeline
        docker push rishabhverma99/my-project-pipeline
