# This workflow will build a Java project with Gradle without relying on the Gradle wrapper properties file.

name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Download and Install Gradle
      run: |
        wget -q https://services.gradle.org/distributions/gradle-7.2-bin.zip
        unzip -q gradle-7.2-bin.zip
        export GRADLE_HOME=$GITHUB_WORKSPACE/gradle-7.2
        export PATH=$GRADLE_HOME/bin:$PATH
      shell: bash

    - name: Build with Gradle
      run: gradle build
